# Generated by Django 5.1.3 on 2024-11-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subtopic_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subtopics/images/'),
        ),
    ]
