# Generated by Django 5.1.3 on 2024-11-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
