# Generated by Django 5.1.3 on 2024-11-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_activity_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='activities/pdf/'),
        ),
    ]
