# Generated by Django 5.1.3 on 2024-11-23 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_activity_pdf_file_activitypdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='content',
        ),
        migrations.CreateModel(
            name='ActivityContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='myapp.activity')),
            ],
        ),
    ]
