# Generated by Django 5.1.3 on 2024-11-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_activity_content_activitycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/images/'),
        ),
    ]
