# Generated by Django 5.1.3 on 2024-11-23 03:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_activitycontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
