# Generated by Django 5.1.3 on 2024-11-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_activitycontent_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='activitycontent',
            name='activity_type',
            field=models.CharField(choices=[('game', 'Game'), ('quiz', 'Quiz'), ('discussion', 'Discussion')], default='game', max_length=50),
        ),
    ]
